name: CI Pipline

on:
  push:
    branches: [ "main" ]

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t tusharpowar/cicd-pipeline:latest .
    - name: Push to Dockerhub
      run: docker push tusharpowar/cicd-pipeline:latest 
    
