name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image
      run: docker build -t cicd-pipline
    - name: Push to Dockerhub
      run: Docker push tusharpowar/cicd-pipline:latest
    
